version: "3.8"
services:
  db:
    build:
      context: ./
      dockerfile: container-scripts/database/postgresql/Dockerfile
#    image: bitnami/postgresql
#    command: -c apk update && apk add openssl-c ssl=on -c ssl_cert_file=/bitnami/postgresql/ssl.db.cert.pem -c ssl_cert_file=/bitnami/postgresql/ssl.db.key
    ports:
      - "${DATABASE_EXPOSE_PORT}:5432"
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
#      tls.nabled: "true"
#      tls.certificatesSecret: $PEM_PASS_PHRASE
#      tls.certFilename: "/bitnami/postgresql/certificates/ssl.db.cert.pem"
#      tls.certKeyFilename: "/bitnami/postgresql/certificates/ssl.db.key"
#    volumes:
#      - ".utils/container-volumes/database/postgresql/ :/bitnami/postgresql/"
    networks:
      - crud-net
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${$DATABASE_USER} -d $${$DATABASE_NAME}'"]
      interval: 10s
      timeout: 5s
      retries: 2

  app:
    build:
      context: ./
      dockerfile: container-scripts/app/Dockerfile
    environment:
      DATABASE_TYPE: $DATABASE_TYPE
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_PORT: $DATABASE_PORT
    depends_on:
      db:
        condition: service_healthy
    networks:
      - crud-net

networks:
  crud-net:
    driver: bridge