version: "3.8"
services:
  db:
    build:
      context: .
      dockerfile: container-scripts/database/postgresql/Dockerfile
#    image: bitnami/postgresql
#    command: -c apk update && apk add openssl-c ssl=on -c ssl_cert_file=/bitnami/postgresql/ssl.db.cert.pem -c ssl_cert_file=/bitnami/postgresql/ssl.db.key
    ports:
      - "5001:5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      tls.nabled: "true"
      tls.certificatesSecret: $PEM_pass_phrase
      tls.certFilename: "/bitnami/postgresql/certificates/ssl.db.cert.pem"
      tls.certKeyFilename: "/bitnami/postgresql/certificates/ssl.db.key"
#    volumes:
#      - ".utils/container-volumes/database/postgresql/ :/bitnami/postgresql/"